name: Test installation

on:
  schedule:
    - cron: "30 23 * * *"  # before nightly builds

jobs:
  test_linux:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install musl-tools
        run: "sudo apt-get install musl-tools"
      - name: Systemd version
        run: "systemd --version"
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
        with:
          components: "cargo,rustc,rust-std"
          toolchain: "1.85"
          targets: "x86_64-unknown-linux-musl"
      - run: |
          cargo build --target=x86_64-unknown-linux-musl \
            --features github_action_install --test github-actions
      - run: |
          cargo test --features github_action_install --test github-actions

  test_other:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25
    strategy:
      max-parallel: 4
      matrix:
        os: [windows-2019, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
        with:
          components: "cargo,rustc,rust-std"
          toolchain: "1.85"
      - run: |
          cargo build --features github_action_install --tests
      - run: |
          cargo test --features github_action_install -- github_action
